### ISSUE TITLE
Re-rendering training frames using w_offset yields very bad results

### ISSUE THREAD

**Issue by ChikaYan** [afruehstueck/VIVE3D#2]
Hi,

Thank you for the brilliant work! 

When I was trying to run the inversion and re-rendering code on some additional video sequences, I obtained very bad results:

![ezgif-1-adc75a0472](https://github.com/afruehstueck/VIVE3D/assets/32335747/71c7a259-f715-4132-8a81-e9d941224ea3)

Basically, during fitting I followed the given code and selected 7 frames out of a 600 frames video for personalized fitting (step 1), then I run invert for all frames in the video. I modified `edit_video.py` file to first disable w editing -- so I just pass original `w_person` and loaded `w_offsets_video` to `generator.generate()` method, which is modified to do the below:

```
    def generate(self, w, yaw=0.0, pitch=0.0, focal_length=None, noise_mode='const', output_all=False, grad=False, w_offset=None,):                 
        # convert angles to camera parameter(s)
        camera_params = self.get_camera_parameters(yaw=yaw, pitch=pitch, focal_length=focal_length)

        # convert w to correct size
        # (,512) -> (1, 512)
        if len(w.shape) == 1:
            w = w.unsqueeze(0)
        
        # (x, 512) -> (x, 1, 512)
        if len(w.shape) == 2:
            w = w.unsqueeze(1)
            
        # repeat to (1, 14, 512)
        if w.shape[1] == 1:
            w = w.repeat(1, self.active_G.backbone.synthesis.num_ws, 1)
        
        num_images = max(len(w), len(camera_params))
        
        # replicate if single w was passed
        if w.shape[0] < num_images:
            w = w.repeat(num_images, 1, 1)
        
        # replicate if single camera parameter was passed
        if camera_params.shape[0] < num_images:
            camera_params = camera_params.repeat(num_images, 1)

        if w_offset is not None:
            w = w + w_offset
        
        assert w.shape[0] == camera_params.shape[0], f'incompatible size of w ({w.shape}) and camera params ({camera_params.shape})'
        
        images = []
        images_raw = []
        depths = []
        self.active_G.to(self.device)
```
I.e., it adds `w_offset` back to duplicated `w`.

May I ask if the result is expected, or did I make a mistake in implementing the re-rendering function?

Many thanks!

**Comment by afruehstueck** [comment]
There is a known issue that our method is not able to handle fast motions - such as in your example video - well, creating nightmare-fuel inversions. 
This is partially due to the fact that we smooth the detected facial landmarks over the course of the video (this is controlled by the parameter `smooth_landmarks` passed to the [`align.get_face_tensors_from_frames`](https://github.com/afruehstueck/VIVE3D/blob/c3b6abd1b1b62dacc1f31ecbbc1cd5ef7e98e3be/vive3D/aligner.py#L94) method) in order to create a more stabilized progression of adjacent frames, at the cost of not being able to handle fast motions well. 
Using a reference face with the facial keypoints in non-optimal locations will create a distorted result in the frame-by-frame inversion, and the optimization does not recover easily once one frame was distorted due to the initialization with the previous step's result.

You could try and see if setting this parameter to `False` would improve your result. 

Another choice could be to not initialise from the previous frame's result but to optimize "from scratch" for each frame (see code fragment starting at [line 832](https://github.com/afruehstueck/VIVE3D/blob/c3b6abd1b1b62dacc1f31ecbbc1cd5ef7e98e3be/vive3D/inset_pipeline.py#L832C13-L832C25))

**Comment by ChikaYan** [comment]
Thx a lot! Yes, after turnning off [align.get_face_tensors_from_frames](https://github.com/afruehstueck/VIVE3D/blob/c3b6abd1b1b62dacc1f31ecbbc1cd5ef7e98e3be/vive3D/aligner.py#L94), the reconstruction results become a lot better:
![ezgif-1-d077c98cf0](https://github.com/afruehstueck/VIVE3D/assets/32335747/603bb0f0-0343-49e3-9524-728a19ef9733)

Thank you so much for your valuable suggestions!

Just one more question, if you compare the inverted results to the actual input:

![vid](https://github.com/afruehstueck/VIVE3D/assets/32335747/bc0feaad-f412-4f23-ae3d-1f35bdac900a)

You would realize that it appears that the camera is moving instead of head is rotating. Would you say this is because EG3D only generates frontalized faces?

**Comment by afruehstueck** [comment]
Happy to hear your results improved 👍🏽 
Yes, that is correct. EG3D is trained on a dataset of faces where the facial keypoints are aligned to the exact same locations in the field of view of the generator. This choice aids the training in learning to generate good facial features, but in our context, also means that the crop of the facial region will move around the video context accordingly, following the facial keypoints.
